/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * custdet.java
 *
 * Created on 16 Mar, 2021, 6:48:07 PM
 */

/**
 *
 * @author rajat
 */
import java.io.File;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
public class custdet extends javax.swing.JFrame {
Connection con;
ResultSet rs;
String q;
Statement st;
int k;
    /** Creates new form custdet */
    public custdet() throws ClassNotFoundException, SQLException {
        initComponents();
        this.setLocation(50, 118);
        Class.forName("java.sql.Driver");
        con=DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel","root","");
        st=con.createStatement();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 20, 40, 40));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 48));
        jLabel2.setForeground(new java.awt.Color(153, 0, 0));
        jLabel2.setText("CLICK ANY ROW TO OPEN THE BILL");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 470, 1060, 50));

        jTextField1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 90, 240, 30));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("SEARCH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 90, 100, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NAME", "MOBILE NO.", "NATIONALITY", "GENDER", "EMAIL", "ID PROOF", "ADDRESS", "CHECKIN DATE", "ROOM NO.", "BED", "ROOM TYPE", "PRICE/DAY"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 1240, 260));

        jLabel4.setBackground(new java.awt.Color(153, 0, 0));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24));
        jLabel4.setForeground(new java.awt.Color(153, 0, 0));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Customer Details Bill.png"))); // NOI18N
        jLabel4.setText("CUSTOMER DETAILS BILL");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 380, 60));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel5.setText("SEARCH BY CHECK OUT DATE");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 220, 30));

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setText("CLEAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 90, 100, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/all pages background.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:

        int a=JOptionPane.showConfirmDialog(null, "Do you really want to close it ?" , "select" , JOptionPane.YES_NO_OPTION );
        if (a==0) {
            this.setVisible(false);
        } else {

        }
}//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            // TODO add your handling code here:
            new custdet().setVisible(true);
            this.setVisible(false);

           
        
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(custdet.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(custdet.class.getName()).log(Level.SEVERE, null, ex);
        }

        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:44
        k=0;
        try {
            DefaultTableModel t=(DefaultTableModel) jTable1.getModel();
            // TODO add your handling code here:
            q = "select * from cust where checkout != 'NULL'";
            rs = st.executeQuery(q);
            while(rs.next()) {
                int id=rs.getInt("id");
                String name=rs.getString("name");
                String ph=rs.getString("ph");
                String nation=rs.getString("nation");
                String gen=rs.getString("gender");
                String ema=rs.getString("email");
                String idp=rs.getString("idp");
                String ad=rs.getString("adress");
                String in=rs.getString("checkin");
                String rno=rs.getString("rno");
                String bed=rs.getString("bed");
                String rt=rs.getString("rt");
                String pr=rs.getString("price");
                t.addRow(new Object[]{id,name,ph,nation,gen,ema,idp,ad,in,rno,bed,rt,pr});
                k=1;
            }
            if(k==0){
                JOptionPane.showMessageDialog(null,"No one checkout today");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(custdet.class.getName()).log(Level.SEVERE, null, ex);
        }
        

    }//GEN-LAST:event_formComponentShown

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    int r=0;
        if(jTextField1.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Fill Check Out Date");
        } else{

            try {
                DefaultTableModel ts=(DefaultTableModel) jTable1.getModel();
                // TODO add your handling code here:
                q = "select * from cust where checkout = '" + jTextField1.getText() + "' ";
                rs = st.executeQuery(q);
               ts.setRowCount(0);
                while(rs.next()) {
                    int id=rs.getInt("id");
                    String name=rs.getString("name");
                    String ph=rs.getString("ph");
                    String nation=rs.getString("nation");
                    String gen=rs.getString("gender");
                    String ema=rs.getString("email");
                    String idp=rs.getString("idp");
                    String ad=rs.getString("adress");
                    String in=rs.getString("checkin");
                    String rno=rs.getString("rno");
                    String bed=rs.getString("bed");
                    String rt=rs.getString("rt");
                    String pr=rs.getString("price");
                    r=1;
                    ts.addRow(new Object[]{id,name,ph,nation,gen,ema,idp,ad,in,rno,bed,rt,pr});
                    

                } if(r==0){
                    JOptionPane.showMessageDialog(null,"No One is Checkout On this date");
                }
            } catch (SQLException ex) {
                Logger.getLogger(custdet.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
}//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int in=jTable1.getSelectedRow();
        TableModel ty=jTable1.getModel();
        String id=ty.getValueAt(in,0).toString();
        try{
                if(new File("E:\\"+id+".pdf").exists() ){
                    Process p=Runtime
                            .getRuntime()

                            .exec("rundll32 url.dll,FileProtocolHandler E:\\"+id+".pdf");
                }
                else{
                    JOptionPane.showMessageDialog(null,"File is not Exits");
                }
            }catch(Exception e){

            }




    }//GEN-LAST:event_jTable1MouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new custdet().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(custdet.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(custdet.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
